# Generated by Django 5.1.1 on 2024-09-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('polarity', models.FloatField()),
            ],
            options={
                'db_table': 'uganda',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ArticleModel',
        ),
    ]
